### ISSUE TITLE
Can't find variable: PIXI

### ISSUE THREAD

**Issue by xjing97** [pixijs/pixi-filters#192] opened 2019-02-22 21:45 UTC
After imported pixi-filters, this error occurs

**Comment by bigtimebuddy** [comment] 2019-02-22 21:58
Please provide more information, such as:
* What tools you're using (WebPack, etc)
* What versions of PixiJS and Pixi-Filters
* Show your code for how you're importing

In general PixiJS needs to be imported before pixi-filters:

```js
import 'pixi.js';
import 'pixi-filters';
```

**Comment by kresli** [comment] 2019-03-14 16:13
"react-scripts": "^2.1.1",
"pixi-filters": "^2.7.1",
"pixi.js": "^5.0.0-rc.2",

```
import * as PIXI from "pixi.js";
import "pixi-filters";
```
`PIXI.filters.DropShadowFilter` is undefined

**Comment by kresli** [comment] 2019-03-14 16:17
also tried `import { DropShadowFilter } from "@pixi/filter-drop-shadow";` and `DropShadowFilter` is undefined

**Comment by bigtimebuddy** [comment] 2019-03-14 16:43
Yup, right now PixiJS filters will have issues with v5 and bundlers, but I know what the issue is. I'll work on resolving this week.

Two potential workarounds:

```js
import "pixi.js/dist/pixi.min.js";
import "pixi-filters";
console.log(PIXI.filters.DropShadowFilter);
```

If that doesn't work, you could also try this:

```js
import * as PIXI from "pixi.js";
window.PIXI = PIXI;
import "pixi-filters";
console.log(PIXI.filters.DropShadowFilter);
```

**Comment by kresli** [comment] 2019-03-14 16:50
Thanks for suggestions, but none of above works. Still undefined.  Here is what I tried
```
import * as PIXI from "pixi.js";
window.PIXI = PIXI;
import { DropShadowFilter } from "@pixi/filter-drop-shadow";
console.log(DropShadowFilter); // <-- exist
console.log(PIXI.filters.DropShadowFilter); // <-- undefined
```
Will probably wait for update then, can't really expose PIXI to window. Thank you for all the hard work. 🙌

**Comment by bigtimebuddy** [comment] 2019-03-14 17:09
Thanks for giving those a try. There is no `PIXI` global to hang the filters on (unless you including filters/pixi via `<script>` element), so your code will probably end up looking something like this:

```js
import * as PIXI from "pixi.js";
import { DropShadowFilter } from "@pixi/filter-drop-shadow";
```

**Comment by kresli** [comment] 2019-03-15 08:00
what if you initialise filter with factory? Something like 
```
import * as PIXI from "pixi.js";
import { DropShadowFilter, createFilter } from "pixi-filter";

const dropShadowFilter = createFilter(PIXI, DropShadow);
```
Maybe I'm off the course here and registering filters directly in PIXI is what community wants.

**Comment by nchase** [comment] 2019-05-10 23:25
This appears to be fixed in pixi-filters 3.x

**Comment by bigtimebuddy** [comment] 2019-05-10 23:26
Thanks for verifying @nchase!

**Closed by bigtimebuddy** 2019-05-10 23:26 UTC

**Comment by trompx** [comment] 2019-05-21 12:03
Hey @bigtimebuddy,

What do you mean it is fixed in 3.x ?

I try to use pixi twist filter (pixi version : 4.8.7) with pixi-filters 3.0.2 :
```
import * as PIXI from 'pixi.js';
import { TwistFilter } from '@pixi/filter-twist';
...
this.fx.twist = new TwistFilter();
this.fx.twist.radius = 0.1;
this.fx.twist.angle = 0.1;
this.fx.twist.offset.x = 0.1;
this.fx.twist.offset.y = 0.1;
```
but I get the error `Cannot set property 'x' of undefined` when it tries to set the offset.

**Comment by bigtimebuddy** [comment] 2019-05-21 13:13
Please don’t pile on this isssue @trompx that’s a new, unrelated issue. The reason you’re having that problem is because you need to set offset = new Point().
