### ISSUE TITLE
Build fails on windows but successful on Linux

### ISSUE THREAD

**Issue by zorrohere** [pixijs/pixi-filters#240] opened 2020-01-23 16:45 UTC
When I try to build this on windows 8.1, I get following error

```
> pixi-filters-monorepo@ build:prod C:\Users\zorro\Desktop\pixifilters
> cross-env NODE_ENV=production rollup -c


filters\adjustment\src\index.js → filters\adjustment\lib\filter-adjustment.cjs.js, filters\adjustment\lib\filter-adjustment.esm.js...
[!] (buble plugin) SyntaxError: Unexpected token (1:8)
filters\adjustment\src\adjustment.frag (1:8)
1 : varying vec2 vTextureCoord;
            ^
SyntaxError: Unexpected token (1:8)
1 : varying vec2 vTextureCoord;`
```

But it builds successfully on Linux on same hardware. On windows, I tried different node versions along with latest lts build. It was successful on linux using latest lts build.

Are there any known issues while building this on Windows? Any guesses what could be wrong?

**Comment by bigtimebuddy** [comment] 2020-12-24 04:18
Can anyone reproduce this? I do not have access to Windows.

**Comment by bigtimebuddy** [comment] 2020-12-30 04:27
Could not reproduce this error.

I was able to install dependencies (`npm install`) and build successfully on Windows 10 and Node.js v14.15.3 (`npm run build:dev` and `npm run build:prod`).

Closing this issue unless someone has more specific information.

**Closed by bigtimebuddy** 2020-12-30 04:27 UTC
Labels: bug
