### ISSUE TITLE
ZoomBlurFilter not working on some iOS devices

### ISSUE THREAD

**Issue by Nokitoo** [pixijs/pixi-filters#193] opened 2019-03-04 09:27 UTC
I tried the [online demo](https://pixijs.io/pixi-filters/tools/demo/) of pixijs filters and the canvas becomes black when using the `ZoomBlurFilter` on some iOS devices:

![img_2694](https://user-images.githubusercontent.com/6523854/53719912-bee7d800-3ea2-11e9-9057-2527f384d2ac.jpg)

Working on:
- iPhone SE iOS 9.3.5 (13G36)

Not working on:
- iPhone 8 iOS 12.0.1 (16A404)
- iPhone X iOS 12.1.4 (16D57)

When enabling the filter, the page freezes for around 5-8 seconds* before turning black.

If I comment [this condition](https://github.com/pixijs/pixi-filters/blob/master/filters/zoom-blur/src/zoom-blur.frag#L76) the filter works correctly and the page does not freeze.

Do you have any idea why there is a such issue on some iOS devices and how to fix it properly?

*freezes only when enabling for the first time after the page loads. After, disabling and enabling the filter multiple times does not make the page freeze.

**Comment by bigtimebuddy** [comment] 2020-12-24 04:35
Duplicate of #216, there's some more context there.

Added `maxKernelSize` as an option to this filter which can be used for these devices by turning the quality down which will render.

**Closed by bigtimebuddy** 2020-12-24 04:35 UTC
