### ISSUE TITLE
Blurs and padding?

### ISSUE THREAD

**Issue by st3v0** [pixijs/pixi-filters#208] opened 2019-05-14 05:01 UTC
The blur filter which comes with pixi.js adjust the filters padding amount based on the strength of the blur. My question is, should the blurs in this project (like motion blur, etc) also adjust the padding amount when, for example, the velocity is increased.

**Comment by bigtimebuddy** [comment] 2020-12-24 04:31
Closing this, duplicate of #238 and there's more information there.

**Closed by bigtimebuddy** 2020-12-24 04:31 UTC
