### ISSUE TITLE
ConvolutionFilter() occured error in IE 11

### ISSUE THREAD

**Issue by wyllisMonteiro** [pixijs/pixi-filters#169] opened 2018-09-21 08:53 UTC
Browser : IE 11.285.17134.0
Device : Desktop
PIXI Version : 4.8.2

I use PIXI to add effects on canvas (brightness, contrast, saturation, and RGB color), so i use AdjustmentFilter() that works well. I need to use convolutionFilter() to create sharpness canvas thank's to matrix. It's work well in all browser but not in ie. I got error : 

Typed array constructor argument is invalid.
filter-convolution.js (8,2187)

I think the problem is at line 39 according to the console

Code : 
<head>
	<meta charset="utf-8">

	<script src="./node_modules/jquery/dist/jquery.min.js"></script>
	<script src="./node_modules/pixi.js/dist/pixi.min.js"></script>
	<script src="./node_modules/@pixi/filter-convolution/lib/filter-convolution.js"></script>

	<script>
		var sharpenFilter = new PIXI.filters.ConvolutionFilter();
		console.log( sharpenFilter );
	</script>
</head>

**Comment by bigtimebuddy** [comment] 2018-09-21 16:49
Looks like the problem is Float32Array in IE11 here:

https://github.com/pixijs/pixi-filters/blob/master/filters/convolution/src/ConvolutionFilter.js#L39

Anyone interested in making a PR to fix this? Should be pretty straightforward. `new Float32Array(matrix.length)` and then "manually" fill the contents of the matrix.

**Comment by wyllisMonteiro** [comment] 2018-09-24 07:53
ok thank's i will try it

**Comment by wyllisMonteiro** [comment] 2018-09-24 12:43
Can you tell me which lines i have to change please?

**Comment by wyllisMonteiro** [comment] 2018-09-25 14:41
i found a solution to resolve my problem. Indeed the problem was Float32Array as said @bigtimebuddy. So I put (changes at line 16-17-18): 

/*!
 * @pixi/filter-convolution - v2.6.0
 * Compiled Wed, 28 Feb 2018 22:04:57 UTC
 *
 * @pixi/filter-convolution is licensed under the MIT License.
 * http://www.opensource.org/licenses/mit-license
 */
! function(e, t) {
    "object" == typeof exports && "undefined" != typeof module ? t(exports, require("pixi.js")) : "function" == typeof define && define.amd ? define(["exports", "pixi.js"], t) : t(e.__filters = {}, e.PIXI)
}(this, function(e, t) {
    "use strict";
    var r = "attribute vec2 aVertexPosition;\nattribute vec2 aTextureCoord;\n\nuniform mat3 projectionMatrix;\n\nvarying vec2 vTextureCoord;\n\nvoid main(void)\n{\n    gl_Position = vec4((projectionMatrix * vec3(aVertexPosition, 1.0)).xy, 0.0, 1.0);\n    vTextureCoord = aTextureCoord;\n}",
        i = "precision mediump float;\n\nvarying mediump vec2 vTextureCoord;\n\nuniform sampler2D uSampler;\nuniform vec2 texelSize;\nuniform float matrix[9];\n\nvoid main(void)\n{\n   vec4 c11 = texture2D(uSampler, vTextureCoord - texelSize); // top left\n   vec4 c12 = texture2D(uSampler, vec2(vTextureCoord.x, vTextureCoord.y - texelSize.y)); // top center\n   vec4 c13 = texture2D(uSampler, vec2(vTextureCoord.x + texelSize.x, vTextureCoord.y - texelSize.y)); // top right\n\n   vec4 c21 = texture2D(uSampler, vec2(vTextureCoord.x - texelSize.x, vTextureCoord.y)); // mid left\n   vec4 c22 = texture2D(uSampler, vTextureCoord); // mid center\n   vec4 c23 = texture2D(uSampler, vec2(vTextureCoord.x + texelSize.x, vTextureCoord.y)); // mid right\n\n   vec4 c31 = texture2D(uSampler, vec2(vTextureCoord.x - texelSize.x, vTextureCoord.y + texelSize.y)); // bottom left\n   vec4 c32 = texture2D(uSampler, vec2(vTextureCoord.x, vTextureCoord.y + texelSize.y)); // bottom center\n   vec4 c33 = texture2D(uSampler, vTextureCoord + texelSize); // bottom right\n\n   gl_FragColor =\n       c11 * matrix[0] + c12 * matrix[1] + c13 * matrix[2] +\n       c21 * matrix[3] + c22 * matrix[4] + c23 * matrix[5] +\n       c31 * matrix[6] + c32 * matrix[7] + c33 * matrix[8];\n\n   gl_FragColor.a = c22.a;\n}\n",
        o = function(e) {
            function t(t, o, n) {
            	t = ( t == undefined ) ? [0,-1,0,-1,5,-1,0,-1,0] : t;
            	o = ( o == undefined ) ? 1000 : o;
            	n = ( n == undefined ) ? 1000 : n;

                e.call(this, r, i), this.uniforms.texelSize = new Float32Array(9), this.matrix = t, this.width = o, this.height = n
            }
            e && (t.__proto__ = e), t.prototype = Object.create(e && e.prototype), t.prototype.constructor = t;
            var o = {
                matrix: {
                    configurable: !0
                },
                width: {
                    configurable: !0
                },
                height: {
                    configurable: !0
                }
            };
            return o.matrix.get = function() {
                return this.uniforms.matrix
            }, o.matrix.set = function(e) {
                this.uniforms.matrix = new Float32Array(e)
            }, o.width.get = function() {
                return 1 / this.uniforms.texelSize[0]
            }, o.width.set = function(e) {
            	console.log( e ) 
                this.uniforms.texelSize[0] = 1 / e
            }, o.height.get = function() {
                return 1 / this.uniforms.texelSize[1]
            }, o.height.set = function(e) {
                this.uniforms.texelSize[1] = 1 / e
            }, Object.defineProperties(t.prototype, o), t
        }(t.Filter);
    e.ConvolutionFilter = o, Object.defineProperty(e, "__esModule", {
        value: !0
    })
}), Object.assign(PIXI.filters, this.__filters);
//# sourceMappingURL=filter-convolution.js.map

**Comment by bigtimebuddy** [comment] 2019-01-07 22:18
Fixed in #183

**Closed by bigtimebuddy** 2019-01-07 22:18 UTC
